<a href="https://colab.research.google.com/github/jewelreddys/Python_lab_activitiy/blob/main/Numpy_Array_Lab13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Array Creation — Detailed Primer


Functions covered: `np.array`, `np.eye`, `np.linspace`, `np.arange`, `np.zeros`, `np.ones`, `np.random` (modern `default_rng`), `np.indices`, plus related utilities.





## `np.array()` — create arrays from Python sequences

**What it does:** Converts Python lists/tuples (or other array-like objects) into a NumPy `ndarray`.

**Signature (common args):** `np.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)`

**Key points / tips:**
- By default `np.array` tries to *infer* the `dtype`. You can pass `dtype=` to force a type.
- `np.array` will usually **copy** from Python lists (so modifying the original list won't change the array). Use `np.asarray` or `np.array(..., copy=False)` if you want to avoid copies when possible.
- If you pass nested lists with different lengths, NumPy creates an array with `dtype=object` (a common pitfall).


In [2]:
import numpy as np

# Basic use
a = np.array([1, 2, 3, 4])
print("a:", a, "dtype:", a.dtype, "shape:", a.shape)

# 2D from nested lists
b = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D b:\n", b, "\ndtype:", b.dtype, "shape:", b.shape)

# Forcing dtype
c = np.array([1, 2, 3], dtype=np.float64)
print("\nForced float dtype c:", c, c.dtype)

# From an existing ndarray -> typically won't copy if dtype and order permit:
orig = np.arange(6).reshape(2,3)
copy_test = np.array(orig)   # by default makes a copy for safety
asarray_test = np.asarray(orig)  # avoids copy
print("\norig.base is", orig.base)  # None, orig owns data
print("copy_test.base is", copy_test.base)  # None (new array)
print("asarray_test.base is", asarray_test.base)  # orig, asarray returns a view (no copy) if possible

# Ragged nested lists -> object dtype (avoid unless intentional)
# ragged = np.array([[1,2],[3,4,5]]) # This line caused the ValueError
# print("\nRagged nested lists produce dtype object:", ragged, ragged.dtype)

a: [1 2 3 4] dtype: int64 shape: (4,)

2D b:
 [[1 2 3]
 [4 5 6]] 
dtype: int64 shape: (2, 3)

Forced float dtype c: [1. 2. 3.] float64

orig.base is [0 1 2 3 4 5]
copy_test.base is None
asarray_test.base is [0 1 2 3 4 5]


## `np.eye()` — identity-like matrices

**What it does:** Creates a 2-D array with ones on a specified diagonal and zeros elsewhere.

**Signature:** `np.eye(N, M=None, k=0, dtype=float, order='C')`

**Notes:**
- `N` is the number of rows; `M` (optional) is the number of columns. If `M` is omitted, a square N×N matrix is created.
- `k` shifts the diagonal: `k=0` main diagonal, `k>0` above main diagonal, `k<0` below.


In [3]:
I = np.eye(4)
print("I (4x4 identity):\n", I)

I2 = np.eye(3, 5, k=1, dtype=int)
print("\nI2 (3x5) with k=1 (diag shifted right):\n", I2)

I (4x4 identity):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

I2 (3x5) with k=1 (diag shifted right):
 [[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


## `np.linspace()` — evenly spaced samples over an interval

**What it does:** Produces `num` evenly spaced samples, optionally including the endpoint.

**Signature:** `np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)`

**Important differences vs `arange`:**
- `linspace` specifies the **number of points** and is therefore preferred for generating floats where you want an exact count (stable for plotting).
- `arange` specifies a step size and can accumulate floating-point rounding errors.


In [4]:
# Basic linspace
lin = np.linspace(0.0, 1.0, 5)
print("linspace(0,1,5):", lin)

# endpoint control & retstep
lin2, step = np.linspace(0, 1, 5, endpoint=True, retstep=True)
print("\nlin2 (with endpoint) =", lin2)
print("step:", step)

lin3, step3 = np.linspace(0, 1, 5, endpoint=False, retstep=True)
print("\nlin3 (endpoint=False) =", lin3)
print("step (when endpoint=False):", step3)

# dtype control
lin_float32 = np.linspace(0, 1, 5, dtype=np.float32)
print("\nDtype float32:", lin_float32, lin_float32.dtype)

linspace(0,1,5): [0.   0.25 0.5  0.75 1.  ]

lin2 (with endpoint) = [0.   0.25 0.5  0.75 1.  ]
step: 0.25

lin3 (endpoint=False) = [0.  0.2 0.4 0.6 0.8]
step (when endpoint=False): 0.2

Dtype float32: [0.   0.25 0.5  0.75 1.  ] float32


## `np.arange()` — ranges (like Python `range`) but producing arrays

**What it does:** Returns evenly spaced values within a given interval.

**Signature:** `np.arange([start,] stop[, step,], dtype=None)`

**Pitfall (common):** When `step` is a float, `arange` can produce results affected by floating point rounding. For float sequences prefer `linspace` for a specific number of points.


In [5]:
# Integer arange (exact)
r1 = np.arange(0, 10, 2)
print("arange(0,10,2):", r1)

# Float arange - caution
r2 = np.arange(0, 1, 0.1)
print("\narange(0,1,0.1):", r2)
print("len:", len(r2))

# Compare with linspace for 11 points (recommended when you need exact endpoints)
r3 = np.linspace(0, 1, 11)
print("\nlinspace(0,1,11):", r3)
print("len:", len(r3))

arange(0,10,2): [0 2 4 6 8]

arange(0,1,0.1): [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
len: 10

linspace(0,1,11): [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
len: 11


## `np.zeros()` and `np.ones()` — arrays filled with zeros/ones

**What they do:** Create arrays of the requested `shape` filled with `0` or `1`.

**Signatures:** `np.zeros(shape, dtype=float, order='C')` and `np.ones(shape, dtype=float, order='C')`.

**Related functions:** `np.zeros_like`, `np.ones_like`, and `np.empty` (uninitialized memory — faster but unsafe if you read values before writing).


In [6]:
z = np.zeros((2,3))
o = np.ones((2,3), dtype=int)
z_like = np.zeros_like(o)  # same shape and dtype as 'o'
empty_example = np.empty((2,2))  # contents are uninitialized (may contain garbage)
print("zeros:\n", z)
print("\nones (int):\n", o)
print("\nzeros_like(o):\n", z_like)
print("\nempty (uninitialized) example:\n", empty_example)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

ones (int):
 [[1 1 1]
 [1 1 1]]

zeros_like(o):
 [[0 0 0]
 [0 0 0]]

empty (uninitialized) example:
 [[0.2 0.4]
 [0.6 0.8]]


## Random numbers — use the modern Generator API (`default_rng`)

NumPy's newer random API (`np.random.default_rng`) is recommended over the legacy `np.random` global functions.

**Why:** reproducibility, better algorithms, thread safety, clearer API.

Common methods on Generator:
- `rng.random(size)` — uniform floats in [0,1)
- `rng.integers(low, high, size)` — random integers
- `rng.normal(loc, scale, size)` — normal distribution
- `rng.choice(a, size, replace, p)` — sample elements

**Reproducibility:** Create a generator with a fixed seed: `rng = np.random.default_rng(12345)`.


In [7]:
# Modern recommended approach
rng = np.random.default_rng(42)
print("rng.random((3,3)):\n", rng.random((3,3)))

print("\nrng.integers(0, 10, size=(3,)):", rng.integers(0, 10, size=(3,)))

print("\nrng.normal(loc=0, scale=1, size=(3,)):", rng.normal(0,1,3))

# Legacy API (still works) but not recommended for new code:
np.random.seed(42)
print("\nLegacy np.random.rand(3):", np.random.rand(3))

rng.random((3,3)):
 [[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]
 [0.7611397  0.78606431 0.12811363]]

rng.integers(0, 10, size=(3,)): [8 4 5]

rng.normal(loc=0, scale=1, size=(3,)): [0.77779194 0.0660307  1.12724121]

Legacy np.random.rand(3): [0.37454012 0.95071431 0.73199394]


## `np.indices()` — generate a grid of indices for given shape

**What it does:** Returns an array representing the indices of a grid of the given `shape`. Useful for advanced indexing, coordinate generation, and image processing.

**Signature:** `np.indices(dimensions, dtype=int, sparse=False)`

**Shape of the result:** For `dimensions=(m,n)`, the result shape is `(2, m, n)` — where the first array contains row indices (0..m-1) and the second contains column indices (0..n-1).

Compare to `np.meshgrid` — `indices` returns integer index grids; `meshgrid` is often used for coordinate matrices for plotting (`x`, `y` floats). `np.indices` supports `sparse=True` to save memory.


In [8]:
idx = np.indices((3,4))
print("idx.shape:", idx.shape)  # (2, 3, 4)
print("\nRow indices (0..2):\n", idx[0])
print("\nCol indices (0..3):\n", idx[1])

# Using sparse=True
idx_sparse = np.indices((3,4), sparse=True)
print("\nWith sparse=True shapes:", [a.shape for a in idx_sparse])
print("Sparse row array shape:", idx_sparse[0].shape, "sparse col array shape:", idx_sparse[1].shape)

idx.shape: (2, 3, 4)

Row indices (0..2):
 [[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]

Col indices (0..3):
 [[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]

With sparse=True shapes: [(3, 1), (1, 4)]
Sparse row array shape: (3, 1) sparse col array shape: (1, 4)


## Extra details & common pitfalls

**Dtype and memory copies**
- `np.array` from Python lists copies by default. `np.asarray` will avoid copying if the input is already an ndarray with the correct dtype.

**Floating point range generation**
- Avoid `np.arange` with floating step sizes when you need an exact number of points — prefer `np.linspace`.

**Ragged nested lists**
- Nested lists with different lengths create an object array (not a numeric array). This breaks vectorized math.

**Contiguous memory / order**
- Arrays can be C-contiguous (`order='C'`) or Fortran-contiguous (`order='F'`). Use `.flags` to inspect (`arr.flags`).

**Broadcasting quick recap**
- When combining arrays of different shapes, NumPy uses broadcasting rules: align trailing dimensions and allow dimensions of size 1 to be stretched.

Examples and tips below.


In [9]:
# Demonstrate dtype & copy behavior
import numpy as np
py_list = [1,2,3]
A = np.array(py_list)
py_list[0] = 99
print("After modifying source list, A =", A)  # A is unaffected (copy)

# Demonstrate asarray avoids copy when given an ndarray
orig = np.arange(6)
v = np.asarray(orig)  # v is a view; no copy
print("\norig.base (None if owns data):", orig.base)
print("v.base (points to orig):", v.base)

# Memory layout flags
mat = np.arange(6).reshape(2,3)
print("\nmat.flags:\n", mat.flags)

After modifying source list, A = [1 2 3]

orig.base (None if owns data): None
v.base (points to orig): None

mat.flags:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



### Broadcasting example

Add a vector to each row of a matrix — broadcasting stretches the vector to match the matrix shape.


In [10]:
M = np.arange(12).reshape(3,4)
v = np.array([10,20,30,40])
print("M:\n", M)
print("\nv:", v)
print("\nM + v (broadcasted):\n", M + v)

M:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

v: [10 20 30 40]

M + v (broadcasted):
 [[10 21 32 43]
 [14 25 36 47]
 [18 29 40 51]]
